name: Deploy to cloud.gov

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy to cloud.gov (Cloud Foundry)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to cloud.gov
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_api: https://api.fr.cloud.gov
          cf_username: ${{ secrets.CF_SERVICE_ACCOUNT_USERNAME }}
          cf_password: ${{ secrets.CF_SERVICE_ACCOUNT_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          command: cf push -f manifest.yaml
